'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace T227679


	Partial Public Class FileDialogControl

		''' <summary>
		''' validationCallback control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected validationCallback As Global.DevExpress.Web.ASPxCallback

		''' <summary>
		''' popup control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected popup As Global.DevExpress.Web.ASPxPopupControl

		''' <summary>
		''' flDialog control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected flDialog As Global.DevExpress.Web.ASPxFormLayout

		''' <summary>
		''' fileManager control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fileManager As Global.DevExpress.Web.ASPxFileManager

		''' <summary>
		''' txFileName control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected txFileName As Global.DevExpress.Web.ASPxTextBox

		''' <summary>
		''' buttonOk control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected buttonOk As Global.DevExpress.Web.ASPxButton

		''' <summary>
		''' buttonCancel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected buttonCancel As Global.DevExpress.Web.ASPxButton
	End Class
End Namespace
